import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: {
  children: React.ReactNode;
  modal: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full">
      <body className={inter.className + " h-full "}>
        {children}
        <Modal>{modal}</Modal>
      </body>
    </html>
  );
}

function Modal({ children }: { children: React.ReactNode }) {
  return <div className="z-[9999]">{children}</div>;
}
