import { cn } from "@/lib/utils";
import "@/styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import React from "react";
import { LiveStateClient } from "./LiveClient";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: [{ rel: "icon", url: "/logo.svg" }],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full">
      <body className={cn(GeistMono.className, " h-full")}>
        <LiveStateClient>{children}</LiveStateClient>
      </body>
    </html>
  );
}

// function Modal({ children }: { children: React.ReactNode }) {
//   return <div className="z-[9999]">{children}</div>;
// }
