import "@/styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: [{ rel: "icon", url: "/logo.svg" }],
};

export default function RootLayout({
  children,
  modal,
}: {
  children: React.ReactNode;
  modal: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}

function Modal({ children }: { children: React.ReactNode }) {
  return <div className="z-[9999]">{children}</div>;
}
